### ISSUE TITLE
maadebugger 运行出现错误

### ISSUE THREAD

**Issue by qbk929** [MaaXYZ/MaaFramework#253]
在使用pip 更新了1.8.4的maafw后，maadebugger无法使用（1.8.2可以使用）。
出错记录如下：

C:\Users\mrqu>maadebugger
MaaFw version: v1.8.4
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\python\Scripts\MaaDebugger.exe\__main__.py", line 4, in <module>
  File "C:\python\Lib\site-packages\MaaDebugger\main.py", line 3, in <module>
    from .webpage import index_page
  File "C:\python\Lib\site-packages\MaaDebugger\webpage\index_page\__init__.py", line 3, in <module>
    from .master_control import main as master_control
  File "C:\python\Lib\site-packages\MaaDebugger\webpage\index_page\master_control.py", line 7, in <module>
    from ...maafw import maafw
  File "C:\python\Lib\site-packages\MaaDebugger\maafw\__init__.py", line 172, in <module>
    maafw = MaaFW()
            ^^^^^^^
  File "C:\python\Lib\site-packages\MaaDebugger\maafw\__init__.py", line 22, in __init__
    Toolkit.init_option("./")
  File "C:\python\Lib\site-packages\maa\toolkit.py", line 34, in init_option
    Library.toolkit.MaaToolkitInitOptionConfig(
OSError: exception: access violation reading 0x0000000000000000

**Comment by MistEO** [comment]
> 这个是因为打包环境更新了，重新装下依赖就好了
> 
> 参考 [MaaAssistantArknights/MaaAssistantArknights#9321](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9321)

好像不是这个问题，我再看看

**Comment by MistEO** [comment]
https://github.com/actions/runner-images/issues/10004
https://github.com/microsoft/STL/releases/tag/vs-2022-17.10

貌似是这个问题，该骂微软了（

**Comment by MistEO** [comment]
https://github.com/MaaXYZ/MaaFramework/commit/1a31a3e78b77c5d9574e50368ec6ad5f7d250ce3

v1.8.6 fixed
