### ISSUE TITLE
下载win-x86无法运行，安装了vc-redist后依旧报错无法运行，dll文件没有问题，错误信息已复制粘贴。

### ISSUE THREAD

**Issue by yysywsCPA** [MaaXYZ/MaaFramework#437]
MFA 遇到了问题
Exception has been thrown by the target of an invocation.
External component has thrown an exception.
详细信息
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at MaaFramework.Binding.Interop.Native.MaaToolkit.<MaaToolkitConfigInitOption>g____PInvoke|12_0(Byte* __userPath_native, Byte* __defaultJson_native)
   at MaaFramework.Binding.Interop.Native.MaaToolkit.MaaToolkitConfigInitOption(String userPath, String defaultJson)
   at MaaFramework.Binding.MaaToolkit.ConfigClass.InitOption(String userPath, String defaultJson)
   at MaaFramework.Binding.MaaToolkit..ctor(Boolean init, String userPath, String defaultJson)
   at MFAWPF.Views.MainWindow..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(XamlType xamlType, Object[] args)
   at MS.Internal.Xaml.Runtime.PartialTrustTolerantRuntime.CreateInstance(XamlType xamlType, Object[] args)
   at System.Xaml.XamlObjectWriter.Logic_CreateAndAssignToParentStart(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.WriteStartMember(XamlMember property)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Windsland52** [comment]
补充：MaaPiCli也闪退，未生成log

**Comment by MistEO** [comment]
什么系统？

在什么目录下运行的？

**Comment by MistEO** [comment]
参考 https://github.com/MaaXYZ/MaaFramework/issues/361#issuecomment-2370262159

- msvcp140.dll
- vcruntime.dll

看下 C:\Windows\System32 里这两个 dll 的版本号，如果是最新的，把这两个 dll 复制到 MFA / MaaPiCli 目录下，然后再试一次

**Comment by yysywsCPA** [comment]
试过将最新版本的msvcp140.dll和vcruntime.dll复制进目录，还是报错，我是win10企业版ltsc系统，解压后运行的目录，无中文路径。

**Comment by MistEO** [comment]
看下 C:\Users\你的用户名\AppData\Local\CrashDumps 这个目录下有什么 maa 相关的 dmp 文件吗？

**Comment by MistEO** [comment]
[config.zip](https://github.com/user-attachments/files/18036363/config.zip)

再试试把 config 文件夹解压放到 MaaPiCli 同目录下，启动 MaaPiCli，有什么报错吗，或者有没有 debug 文件夹生成？

**Comment by MistEO** [comment]
在群友的帮助下找到了问题所在，https://github.com/MaaXYZ/MaaFramework/commit/96030703559856c70cde025a3abd50e4a4c112b6

![PC~@_)NK`DLGFNZ 4R0M}2](https://github.com/user-attachments/assets/e87d8c8a-0bb2-4caf-8b92-fb189ff60751)
![4N@W$RJXIZ G5U7WJ}PY N](https://github.com/user-attachments/assets/adf895bf-6817-445f-a1cf-7e080ff04254)
![~ICK{6_5@30IXV1W YC_%J8](https://github.com/user-attachments/assets/2eda7e69-9e2d-4b32-895d-85f0a9cf268d)

之后的版本会修复一下。

如果急着用可以先拿这个临时包凑合一下： https://github.com/MaaXYZ/MaaFramework/actions/runs/12213902970

**Comment by MistEO** [comment]
之后的版本会修复一下

如果急着用可以先拿这个临时包凑合一下： https://github.com/MaaXYZ/MaaFramework/actions/runs/12213902970

**Comment by MistEO** [comment]
v2.3.0-beta.3 fixed
