### ISSUE TITLE
Image Cropper启动报错UnboundError

### ISSUE THREAD

**Issue by Oarwind** [MaaXYZ/MaaFramework#495]
```
Traceback (most recent call last):
  File "C:\Users\...\ImageCropper\main.py", line 111, in <module>
    controller = parse_args()
  File "C:\Users\...\ImageCropper\main.py", line 90, in parse_args
    if 0 <= i < len(device_list):
            ^
UnboundLocalError: cannot access local variable 'i' where it is not associated with a value
```

检查了一下，这个i貌似的确没赋上值……

````python
// main.py line 84
    if t == 1:
        device_list = Toolkit.find_adb_devices()
        if len(device_list):
            for i, d in enumerate(device_list):
                print(f"{i:>3} | {d.address:>21} | {d.name}")
            i = int(input("Please select the device (ENTER to pass): "))
        if 0 <= i < len(device_list):
            device_serial = device_list[i].address
            return AdbController(adb_path=device_list[i].adb_path,
                                 address=device_serial,
                                 screencap_methods=adb_screencap_method)
```
这个if整体缩进之后就能跑了orz

**Comment by neko-para** [comment]
@Oarwind 怎么说呢，这玩意现在没啥人用了，大概
主要都用MFA Tools和VSC插件了
![6662a854e35fdb9441d7bf0156d7ff67](https://github.com/user-attachments/assets/e56692f1-b74f-4846-8050-1f1a48d29ed3)

**Comment by moomiji** [comment]
怎么说呢，查不到设备才会触发这个bug）
