### ISSUE TITLE
java在调用tasker.postPipeline().wait()时报错

### ISSUE THREAD

**Issue by SCzfdf** [MaaXYZ/MaaFramework#502]
```java
    // 调用代码
    new Thread(this::loopScreenshot).start();


    @SneakyThrows
    private void loopScreenshot() {
        try (Tasker tasker = new Tasker()){
            tasker.bind(resource, controller);
            while (true) {
                long now = System.currentTimeMillis();
                TaskFuture<TaskDetail> taskFuture = tasker.postPipeline("screenshot",
                        Map.of("screenshot",
                                Map.of("action", "Custom",
                                        "custom_action", "screenshotAction",
                                        "pre_delay", 0,
                                        "post_delay", 0)
                        ));
                taskFuture.wait();
                TaskDetail taskDetail = taskFuture.get();
                log.info("Screenshot time:{}, result:{}", System.currentTimeMillis() - now, taskDetail);
            }
        }
    }
```

Exception in thread "Thread-2" java.lang.IllegalMonitorStateException: current thread is not owner
	at java.base/java.lang.Object.wait(Native Method)
	at java.base/java.lang.Object.wait(Object.java:338)
	at com.sczfdf.maa.random.dice.handler.StartHandler.loopScreenshot(StartHandler.java:121)
	at java.base/java.lang.Thread.run(Thread.java:842)

**Comment by MistEO** [comment]
@hanhuoer 来瞅瞅_(:з」∠)_

**Comment by SCzfdf** [comment]
> @hanhuoer 来瞅瞅_(:з」∠)_

这是项目地址
https://github.com/SCzfdf/maa-random-dice

**Comment by hanhuoer** [comment]
抱歉来晚了，刚刚才收到消息... @MistEO 

回到正题，我猜你是想用 `taskFuture.waiting();` 这个方法？

因为 Java 这边 `wait` 是内置函数，所以在实现这一块逻辑的时候调整了这个方法名，你改过来试试看

@SCzfdf 

<img width="830" alt="image" src="https://github.com/user-attachments/assets/987d5739-2165-4e34-96f4-4495a61f95ed" />

**Comment by SCzfdf** [comment]
> 抱歉来晚了，刚刚才收到消息... @MistEO
> 
> 回到正题，我猜你是想用 `taskFuture.waiting();` 这个方法？
> 
> 因为 Java 这边 `wait` 是内置函数，所以在实现这一块逻辑的时候调整了这个方法名，你改过来试试看
> 
> @SCzfdf
> 
> <img alt="image" width="830" src="https://private-user-images.githubusercontent.com/28647233/400126659-987d5739-2165-4e34-96f4-4495a61f95ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5Nzk1MDAsIm5iZiI6MTczNTk3OTIwMCwicGF0aCI6Ii8yODY0NzIzMy80MDAxMjY2NTktOTg3ZDU3MzktMjE2NS00ZTM0LTk2ZjQtNDQ5NWE2MWY5NWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA0VDA4MjY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZjA3MWY0Y2FkYWJlODQzM2ZjOTU5ZmRmMDRhNmRlYTg2ZDRhZGEyMDkzNzliZmQ4NDAyOTZmNDBlMzBkYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gYk_5hcnmu0k2-3zif6KH53t_fUzieikTuSzsj8k0mA">


可以了 谢谢, 还有个问题能帮我看看吗? 
https://github.com/MaaXYZ/MaaFramework/issues/501
